version: '3.7'
services:
    frontend_seed:
        container_name: frontend-seed
        image: node:10.15.1
        command: bash -c ${DOCKER_CMD}
        working_dir: /usr/app
        volumes:
            - ./:/usr/app
        ports:
            - ${PORT}:${PORT}
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
